### ISSUE TITLE
Improve quality/helpfulness of Hound comments

### ISSUE THREAD

**Issue by raphaelcm** [houndci/hound#1012]
Hound comments like, "Space inside parentheses detected" and "Line/Method too long" are authoritarian in tone and not particularly helpful. Rather than educating the pull request author, it's just barking at them about having violated some rule that they may not understand or even know about.

These comments could be improved by doing two things:

1. Pointing the pull request author to the relevant section of the style guide
  * e.g. sharing the `StyleGuide` url, if there is one
2. Helping the user understand the WHY: why Hound barks at this, and what the author should do next.
  * Could allow customization of Hound comment text in YML file, so teams can do what's best for them.
  * For example, instead of saying "Method too long", we'd like Hound to say "The new method you've written is longer than we would normally expect. Is it doing more than one thing? (Read up about SRP [here](https://blog.8thlight.com/cory-foy/2012/08/07/thinking-differently-about-srp.html).)"

**Comment by jakecraige** [comment]
I think we probably all agree this would be a nice addition but the maintenance cost of this would be (potentially)pretty high. 

Because Hound is built off external linters, we pass through the error messages they give us back to the user. To support this we'd likely have to map all of their errors to our own format and then maintain a more friendly translation. The burden of maintaining this is that when new rules are added or existing ones format/wording changes, the mappings break, so they constantly have to be maintained. This also makes upgrading versions more difficult because we have to verify everything still works.

That being said, this is currently possible with Hound's architecture because any linter can give back whatever errors it wants. For the ruby linter, you would want to map RuboCop's error message to a more friendly one [here](https://github.com/thoughtbot/hound/blob/master/app/models/linter/ruby.rb#L21). You'd probably attempt to map it and fall back to the original message if it fails. Maybe reporting that to some service so someone is alerted and can provide a mapping for that.

I'd be curious to hear the rest of the Hound team's thoughts on this kind of thing. I think it may have been discussed somewhere before but I couldn't find it.

**Comment by raphaelcm** [comment]
Does the `violation` object in that method (`Linter::Ruby#perform_file_review`) have info about what rule was violated?

If so, could we specify a custom error message? e.g.:

```
Metrics/MethodLength:
  Description: Avoid methods longer than 10 lines of code.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#short-methods
  Enabled: true
  CountComments: false
  Max: 10
  CustomMessage: "The new method you've written is longer than we would normally expect. Is it doing more than one thing?"
```

Then in Linter::Ruby you use `CustomMessage` if present for the rule that was violated, else fall back to the message from the external linter.
