### ISSUE TITLE
scss exclude syntax

### ISSUE THREAD

**Issue by hovancik** [houndci/hound#1018]
I am not sure what I am doing wrong but I am not able to make hound ignore scss file: 

code is here: 
https://github.com/DiscoverBSD/talks/pull/1

```
exclude:
  - "source/css/_normalize.css.scss"
```

what I did: 

addded .hound.yml

```
ruby:
  config_file: .ruby-style.yml
scss:
  config_file: .scss-style.yml

fail_on_violations: true
```

copied default scss yml from https://houndci.com/configuration#scss and added exclude .I have the same syntax (that I use in another app [private repo]), but here it's not ignoring it. 

I tried different syntax for exclude but non seems to work for me ;/

**Comment by gylaz** [comment]
I took a look at your PR and it seems that you configured Hound Scss linter after Hound left comments. Can you try deleting a few comments that Hound left on the excluded file, then push another commit?

**Comment by hovancik** [comment]
committed 16 minutes ago, hound is still checking. I guess that's not right.

**Comment by gylaz** [comment]
It looks like it's still commenting. We'll take a look. Thanks for reporting this.

**Comment by hovancik** [comment]
so it finished:  hound — 77 violations found.

**Comment by rsalevsky** [comment]
We have the same problem, see https://github.com/crowbar/crowbar-core/pull/144 as reference. This https://github.com/SUSE-Cloud/crowbar-core/commit/2b730a5fb4fdb0229a07d56fd407f28b517baece  is the commit where we exclude the scss files. Running scss-lint locally works fine.

The curios thing is that it worked the the last weeks for us but since today it stopped working.

**Comment by tboerger** [comment]
And another case where it happens => https://github.com/crowbar/crowbar-core/pull/193
Even with that config:

```
linters:
  NestingDepth:
    max_depth: 6

exclude:
  - "crowbar_framework/vendor/**/*"
```

**Comment by beaktor** [comment]
Sorry to piggyback off of this issue, but following the docs I ran into problems getting the exclude to work:

The documentation asks for a `scss:` line inside the example `.scss-style.yml` file, which didn't seem to work if I pasted it underneath the first few lines. If I removed that line, then I had no problems:

```yaml
# Default application configuration that all configurations inherit from.

scss_files: "**/*.scss"
plugin_directories: ['.scss-linters']

exclude:
  - "app/styles/_sc-icons-bootstrap.scss"
...
```

I'd like to open this PR to update the documentation"
https://github.com/houndci/hound/compare/master...beaktor:patch-1

Cross-confirmed with an example in the linter documentation:
https://github.com/brigade/scss-lint#configuration
