### ISSUE TITLE
TargetRubyVersion in .rubocop.yml is ignored

### ISSUE THREAD

**Issue by bensaufley** [houndci/hound#1109]
Hound keeps reacting to Ruby 2.3 syntax with the below:

> unexpected token error
> (Using Ruby 2.0 parser; configure using `TargetRubyVersion` parameter, under `AllCops`)

In our .rubocop.yml file:

```yml
AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
    - "spec/fixtures/**/*"
  UseCache: false
  DefaultFormatter: progress
  DisplayStyleGuide: true
  DisplayCopNames: false
  TargetRubyVersion: 2.3
```

Locally, running `rubocop` adheres to TargetRubyVersion 2.3, but Hound does not appear to acknowledge it. Hound is clearly implementing the styles we have in .rubocop.yml, so it's not an issue of ignoring the entire config. It's just ignoring this line. FWIW, here's our .hound.yml, which is at the root of the project just like .rubocop.yml:

```yml
eslint:
  enabled: true
  config_file: .eslintrc
haml:
  enabled: true
  config_file: .haml-lint.yml
javascript:
  enabled: false
ruby:
  enabled: true
  config_file: .rubocop.yml
scss:
  enabled: true
  config_file: .scss-lint.yml
```

Normally I'd post my env details, but since this is happening on GitHub, I'm not sure what other information to give; please let me know what else I can provide.
