### ISSUE TITLE
Cannot ignore directories while using ESLint?

### ISSUE THREAD

**Issue by benjamincharity** [houndci/hound#1176]
Doing some test runs with this and notice that I cannot seem to ignore certain directories while using ESLint. So Hound is commenting all over the files within dist. (for components released via bower, dist must be tracked)

I see in the [docs](https://houndci.com/configuration#javascript) that you can set an ignore file for JSHint, is there a way to do this with ESLint yet? Or is this simply a case of using something that is in beta (the ESLint functionality)?

---

My hound.yml file:

```yml
# Hound Configuration
# https://houndci.com/configuration

# Tell GitHub to fail the PR if any violations are found
fail_on_violations: true

# Disable JavaScript checking (jshint)
# Note: We must explicitly disable this (all supported, non-beta languages are reviewed by default)
javascript:
  enabled: false

# Enable ESLint and point to the config file
# Note: Since the ESLint plugin is in beta, we need to explicitly enable
eslint:
  enabled: false
  config_file: .eslintrc
  ignore_file: .eslintignore
```
