### ISSUE TITLE
Missing semicolon on nodejs app

### ISSUE THREAD

**Issue by mkermani144** [houndci/hound#1193]
Hound comments if semicolons are missing in nodejs. Is there anyway to ignore `Missing semicolon` comments?

**Comment by mkermani144** [comment]
I found the solution. I can use a `.hound.yml` file like this:
```yml
javascript:
  enabled: true
  config_file: js/.jshintrc
```
and a `.jshintrc` like this:
```js
{
  "asi"      : true
}
```
