### ISSUE TITLE
Hound ignores .rubocop.yml

### ISSUE THREAD

**Issue by williamn** [houndci/hound#1253]
Hello.

It seems Hound ignores my .rubocop.yml by still commenting: Line is too long. [103/80].

Here is my .hound.yml

```yaml
ruby:
  config_file: .rubocop.yml

fail_on_violations: true
```

and my .rubocop.yml

```yaml
inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true
```

and my .rubocop_todo.yml

```yaml
# This configuration was generated by
# `rubocop --auto-gen-config`
# on 2016-11-18 12:35:08 +0700 using RuboCop version 0.45.0.
# The point is for the user to remove these configuration records
# one by one as the offenses are removed from the code base.
# Note that changes in the inspected code, or installation of new
# versions of RuboCop, may require this file to be generated again.

# Offense count: 1
# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Exclude:
    - 'bin/spring'

# Offense count: 29
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives.
# URISchemes: http, https
Metrics/LineLength:
  Exclude:
    - 'Gemfile*'
    - 'config/**/*'
    - 'db/*'
    - 'test/test_helper.rb'
    - 'Rakefile'

# Offense count: 1
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

# Offense count: 10
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'db/migrate/*'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: empty_lines, no_empty_lines
Style/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 15

# Offense count: 2
# Cop supports --auto-correct.
Style/SpaceInsideBrackets:
  Exclude:
    - 'config/environments/production.rb'

# Offense count: 11
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'bin/spring'
    - 'config/environments/production.rb'
    - 'config/puma.rb'
    - 'db/schema.rb'
```

Any suggestion will appreciated. Thanks!

**Comment by vladra** [comment]
Similar issue. Rubocop is not linting properly

**Comment by davidwessman** [comment]
Did you get this to work @williamn @vladra ?

**Comment by vladra** [comment]
@davidwessman nope. I switched to system.danger on the CI servers

**Comment by jakecraige** [comment]
@williamn thanks for the report. Can you provide more context onto which lines/files it's commenting about the line length? From the config you are excluding some files, but not all of them, so I would expect to see it on some of them. 

One way to test this would be to run rubocop locally on your project and see if it gives the same errors, if it does, you'll need to modify your configuration to get the results you want.

If you're still having trouble feel free to reach out to our support at hound@thoughtbot.com so we can assist further.

**Comment by tonyta** [comment]
Hey all. I'm having the same problem. I think it has something do to with nested `inherited_from` (https://github.com/houndci/hound/pull/1148). It seems that Hound will only see the file pointed to directly by `.hound.yml` but fails to follow any inheritance.

In the above example, `.hound.yml` points to `.rubocop.yml`. The latter inherits from `.rubocop_todo.yml`, but Hound doesn't follow the inheritance, so it loads defaults and runs that instead. 

I've been having similar problems myself. Additionally, Rubocop runs this with no problem locally, pulling in all inherited configurations. Only after I flattened the configuration into one file did Hound worked for me.

Hope this helps!

**Comment by equivalentideas** [comment]
We're having the same issue, but it doesn't appear to be related to nesting.

We're using a [whitelisting approach to RuboCop](https://github.com/openaustralia/publicwhip/blob/master/.rubocop.yml#L4), but [Hound is making comments](https://github.com/openaustralia/publicwhip/pull/1147#discussion_r111106139) about cops we haven't enabled:

![screen shot 2017-04-18 at 6 17 45 pm](https://cloud.githubusercontent.com/assets/1239550/25121027/9f6eb652-2463-11e7-964f-2de44f1f0689.png)

Running `bundle exec rubocop` locally doesn't show these warnings, just the ones switched on in our [`.rubocop.yml`](https://github.com/openaustralia/publicwhip/blob/master/.rubocop.yml)

[Our `.hound.yml`](https://github.com/openaustralia/publicwhip/blob/master/.hound.yml) appears to be correctly following [your documention](https://houndci.com/configuration#ruby).

I disabled hound on the repo so it doesn't annoy our contributors while we fix this ;-) Thanks for this tool and making it free for open source ❤️

**Comment by bdubaut** [comment]
Same here. Rubocop explicitly says not to lint `db/schema.rb` but Hound still lints it:
![screen shot 2017-04-26 at 10 37 38](https://cloud.githubusercontent.com/assets/798319/25425473/65808efc-2a6c-11e7-8759-27a3f75cc6e9.png)

and as you can see:
```yaml
# .hound.yml
fail_on_violations: true
ruby:
  enabled: true
  config_file: api/.rubocop.yml

# api/.rubocop.yml
AllCops:
  Exclude:
    - "db/schema.rb" # adding this line to the file did not change anything to the Hound behaviour
    - "db/**/*"
    - "bin/*"
    - "config/boot.rb"
...
```

Is there something like a default .rubcop.yml file that takes over the repo's one somehow?

**Comment by gylaz** [comment]
@bdubaut looks like your DB schema is in `api/db/schema.rb` but it looks like you're missing that `api/` path in your excludes.

**Comment by bdubaut** [comment]
@gylaz well, here's the (simplified) file tree:
```
├── api
│   ├── db
│   │   └── schema.rb
│   ├── .rubocop.yml
├── .hound.yml
```
So if i follow my arborescence, I am passing the right path for `.rubocop.yml` to Hound, and inside the rubocop config file, I am passing the correct exclude path.

**Comment by gylaz** [comment]
When Hound runs RuboCop it places the `.rubocop.yml` is at the top level. We lint one file at the time, and don't copy the structure of the project, to avoid storing our user's code. So the `linters` service will run it like this:
```
rubocop -c .rubocop.yml api/db/schema.rb
```

**Comment by androse** [comment]
We're having similar issues, although Hound seems to be commenting on rules that are neither defined in our `.rubocop.yml` nor are Rubocop defaults.

We're getting:

> Place the . on the previous line, together with the method call receiver.

and

> %w-literals should be delimited by ( and ).

Even though our `.rubocop.yml` looks like:
```yml
...
Layout/DotPosition:
  Description: 'Checks the position of the dot in multi-line method calls.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#consistent-multi-line-chains'
  EnforcedStyle: leading
  Enabled: true
...
Style/PercentLiteralDelimiters:
  Description: 'Use `%`-literal delimiters consistently'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#percent-literal-braces'
  Enabled: true
...
```

Running Rubocop locally doesn't result in any offences.

We're big fans of hound so we'd love to help get this fixed.

**Comment by gylaz** [comment]
@androse Check to see if your repo is configured for org-level. If so, you'll need to update the rules in our org-level repo as well.

**Comment by androse** [comment]
That seems to have worked @gylaz! Thanks for your help.

**Comment by teoljungberg** [comment]
Is anyone experiecing this issue? Or can it be closed?

**Comment by prikha** [comment]
We have the same issue:

Hound is configured to consume `.rubocop.yml`
```
# .hound.yml
fail_on_violations: true

ruby:
  config_file: .rubocop.yml
```

Our config is as follows:
```
# .rubocop.yml
# For all options see https://github.com/bbatsov/rubocop/tree/master/config
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - app/assets/**/*
    - app/views/**/*
    - script/**/*
    - spec/**/*
    - public/**/*
    - config/**/*
    - db/**/*
    - doc/**/*
    - lib/**/*
    - vendor/**/*
    - provisioning/**/*

Rails:
  Enabled: true

StringLiterals:
  Enabled: false

Documentation:
  Enabled: false

SignalException:
  Enabled: false

AsciiComments:
  Enabled: false

TrailingBlankLines:
  Enabled: true

Style/ModuleFunction:
  Enabled: false

# Avoid methods longer than 30 lines of code
MethodLength:
  CountComments: false  # count full line comments?
  Max: 30

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 130

# Don't enforce specific
Style/ClassAndModuleChildren:
  Enabled: false

Style/SpaceBeforeBlockBraces:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: leading

# Don't require utf-8 encoding comment
Encoding:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: true
```

Then hound produces:

```
Use %i or %I for an array of symbols.
```

However  `rubocop -c .rubocop.yml /app/lib/new_file.rb` does not complain about array of symbols.
Is there any fallback logic? Or should our rubocop.yml be copied from some default and tuned afterwards?
