### ISSUE TITLE
New Rubocop Cop Breaks Hound

### ISSUE THREAD

**Issue by cshaffer** [houndci/hound#1370]
With hound's latest upgrade of rubocop, a new cop was introduced called `Style/InverseMethods` that requires config that has serialized symbols, as part of this PR: https://github.com/bbatsov/rubocop/pull/4000

The default config in rubocop for this new cop looks like this (note the method names that are symbols, e.g. `:any?`, `:even?`, etc):

```yaml
Style/InverseMethods:
  Enabled: true
  # `InverseMethods` are methods that can be inverted by a not (`not` or `!`)
  # The relationship of inverse methods only needs to be defined in one direction.
  # Keys and values both need to be defined as symbols.
  InverseMethods:
    :any?: :none?
    :even?: :odd?
    :==: :!=
    :=~: :!~
    :<: :>=
    :>: :<=
    # `ActiveSupport` defines some common inverse methods. They are listed below,
    # and not enabled by default.
    #:present?: :blank?,
    #:include?: :exclude?
  # `InverseBlocks` are methods that are inverted by inverting the return
  # of the block that is passed to the method
  InverseBlocks:
    :select: :reject
    :select!: :reject!
```

Because of this, your call to `Yaml.safe_load` in `Parser` raises since you only whitelist serialization of `Regexp` and not `Symbol`.  Rubocop's own config loader also added `Symbol` to its own whitelisting in the same PR that introduced the cop: https://github.com/bbatsov/rubocop/pull/4000/files#diff-e2fc41e8fa0504d203570a8d822495afR171

The ramification of all of this is that if your rubocop config includes this cop, hound will fail to run on your pull request and display an error message: `Error parsing config for: ruby. Click "details" for assistance.`
