### ISSUE TITLE
Hound not respecting .sass-lint.yml rules

### ISSUE THREAD

**Issue by bmatto** [houndci/hound#1386]
Our config file looks like this:

```yml

coffeescript:
  config_file: .coffeelint.json

javascript:
  enabled: false

eslint:
  enabled: true
  config_file: client/.eslintrc

ruby:
  config_file: .rubocop.yml

scss-lint:
  enabled: false

sass-lint:
  enabled: true
  config_file: .sass-lint.yml

```

Where the .sass-lint.yml file and the .hound.yml file are in the root of the directory.  The pertinent .sass-lint.yml configuration looks like this...

```yml
files:
  include:
    - '**/*.s+(a|c)ss'
  ignore:
    - '**/node_modules/**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: false
```

From what I can tell hound is using sass-lint, however it is using the default configuration that ships with hound.  Would greatly appreciate any thoughts on where we have gone astray.

Thanks!
