### ISSUE TITLE
Hound gets stuck on PRs when rupocop doesn't return anything

### ISSUE THREAD

**Issue by maria-v** [houndci/hound#1653]
One of the ways to reproduce:
in `.rubocop.yml` change
```
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
```
to 
```
Style/TrailingCommaInLiteral:
  Enabled: false
```

then in .hound.yml:
```
ruby:
  enabled: true
  config_file: .rubocop.yml
```

If you run rubocop locally, it'll not output anything. Then, if you push it and open a PR, the hound will get perpetually stuck in "Pending — Hound is busy reviewing changes..." state (very hard to debug it in this state).
