### ISSUE TITLE
Support for Rubocop 0.65.0

### ISSUE THREAD

**Issue by jmgarnier** [houndci/hound#1682]
While upgrading to ruby 2.6, I came across the problem described #1680 

I did set up `.hound.yml` with : 
```
ruby:
  enabled: true
  config_file: .rubocop.yml
rubocop:
  version: 0.65.0
coffee_script:
  enabled: true
  config_file: .coffeescript-style.json
jshint:
  ignore_file: .jshintignore
sass-lint:
  enabled: false
scss:
  enabled: false
```

=> "The configured rubocop version is not supported"
![image](https://user-images.githubusercontent.com/8051/54119708-4202b400-43f6-11e9-8b3e-1ac1a13d5031.png)
