### ISSUE TITLE
Is hound reading my eslint file?

### ISSUE THREAD

**Issue by kapso** [houndci/hound#1687]
Why am I getting these...

- `Parsing error: 'import' and 'export' may appear only with 'sourceType: module'`
- `Missing trailing comma comma-dangle`

...even though I have `.eslintrc.json`

```json
{
  "parser": "babel-eslint",
  "extends": "airbnb",
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "comma-dangle": ["error", "never"]
}
```

...and my `.hound.yml`
```yml
eslint:
  enabled: true
  config_file: .eslintrc.json

ruby:
  config_file: .rubocop.yml

scss:
  enabled: false
```
