### ISSUE TITLE
`inherit_gem` configuration not supported by Hound?

### ISSUE THREAD

**Issue by smridge** [houndci/hound#1786]
**Error Message**:
`Unable to find gem hl_ruby_style; is the gem installed? Gem::MissingSpecError`

This was originally a private gem, found related error in https://github.com/houndci/hound/issues/1737#issuecomment-523973676https://github.com/houndci/hound/issues/1737%23issuecomment-523973676 . The gem was made public and published to [ruby gems](https://rubygems.org/gems/hl_ruby_style). I'm still encountering the same errors.

In `.rubocop.yml`
```yaml
inherit_gem:
  hl_ruby_style:
    - default.yml
```

Perhaps there is a `hound.yml` setting? I couldn't seem to find `hound.yml` options, the closest I found was http://help.houndci.com/en/articles/2137566-rubocop . In attempt of "giving it a go", I tried:
```yaml
rubocop:
  enabled: true
  version: 0.80.0
  inherit_gem:
    hl_ruby_style:
      - default.yml
  config_file: .rubocop.yml
```
and unfortunately no luck.

Does hound support `inherit_gem`?
