### ISSUE TITLE
Upgrade SwiftLint to 0.41.0 to Allow Inclusive Languages

### ISSUE THREAD

**Issue by shiki** [houndci/hound#1825]
We're removing non-inclusive languages from our [open source project](https://github.com/woocommerce/woocommerce-ios). One of the remaining items is the `whitelist_rules` configuration we use for SwiftLint. 

SwiftLint [version 0.41.0](https://github.com/realm/SwiftLint/blob/master/CHANGELOG.md#0410-worlds-cleanest-voting-booth) adds an inclusive version for this, `only_rules`. At the time of this writing, Hound [only supports 0.27.0](http://help.houndci.com/en/articles/2461415-supported-linters).

We tried setting the version directly in `.hound.yml`:

```yaml
swiftlint:
    config_file: .swiftlint.yml	    config_file: .swiftlint.yml
    version: 0.41.0
```

But, as expected, Hound responded with:

```
Some files could not be reviewed due to errors:

The configured swiftlint version is not supported. 
See a list of supported versions on our docs page.
```

It'd be great if 0.41.0 for SwiftLint is supported. 🙂
