### ISSUE TITLE
Failed to load parser '@babel/eslint-parser' declared in '.eslintrc':

### ISSUE THREAD

**Issue by dannyrb** [houndci/hound#1838]
Does hound support `@babel/eslint-parser`? If so, what would cause this to fail on CI but pass locally?

![Screen Shot 2021-03-24 at 4 42 21 PM](https://user-images.githubusercontent.com/5797588/112380641-dae78d80-8ca6-11eb-9b7f-52e8faeb1cfa.png)

**Comment by gylaz** [comment]
Which version of ESLint are you using with Hound? He have added support for `@babel/eslint-parser` to ESLint v7.7.0.

**Comment by phyzical** [comment]
hey @gylaz i can confirm its not found with the following hound.yml

```
eslint:
  enabled: true
  config_file: .eslintrc.yml
  ignore_file: .eslintignore
  version: 7.7.0
```
