### ISSUE TITLE
.eslintrc format is invalid

### ISSUE THREAD

**Issue by pavelbonda** [houndci/hound#1844]
Yesterday I started getting `.eslintrc format is invalid` error, and I'm struggling to find a reason. It is reproducible with following configs:

```yml
# .hound.yml

fail_on_violations: true

rubocop:
  version: 0.80.0
  config_file: .rubocop.yml

eslint:  
  enabled: true  
  version: 5.7.0  
  config_file: .eslintrc
```

```json
# .eslintrc

{
  "rules": {},
  "env": {
    "es6": true,
    "browser": true
  },
  "extends": "eslint:recommended"
}
```
