### ISSUE TITLE
Feature request: allow to install eslint plugins and config from .eslintrc

### ISSUE THREAD

**Issue by leosuncin** [houndci/hound#1857]
I use this eslint config

```json
{
  "extends": ["next"],
  "plugins": ["deprecation"],
  "overrides": [
    {
      "files": ["**/*.ts", "**/*.tsx"],
      "rules": {
        "deprecation/deprecation": "warn"
      }
    },
    {
      "files": ["**/*.spec.ts", "**/*.spec.tsx"],
      "plugins": ["jest", "jest-formatting", "testing-library"],
      "env": {
         "jest": true
      },
      "extends": [
        "plugin:jest/recommended",
        "plugin:jest/style",
        "plugin:jest-formatting/strict",
       "plugin:testing-library/react"
      ]
    }
  ]
}
```

and this `.hound.yml`

```yaml
eslint:
  enabled: true
  version: 7.7.0
  config_file: .eslintrc.json
  ignore_file: .eslintignore

jshint:
  enabled: false
```

and I'm getting the follow messages messages in the PR from Hound

![](https://user-images.githubusercontent.com/4307697/132974335-5a0a3923-3502-4633-943c-887eb55cd349.png)

Also there are some open issues related to missing plugins #1845 #1841 #1838 [etc](https://github.com/houndci/hound/issues?q=is%3Aissue+is%3Aopen+eslint)

This can be done by installing eslint's packages in `package.json` or add a setting to pass an array of packages to Hound  

```yaml
eslint:
 enabled: true
 version: 7.7.0
 config_file: .eslintrc.json
 ignore_file: .eslintignore
 plugins:
     - eslint-config-next
     - eslint-plugin-deprecation
     - eslint-plugin-jest
     - eslint-plugin-jest-formatting
     - eslint-plugin-testing-library
jshint:
 enabled: false
```

This will be helpful for you because it will prevent that people open a new issue for every eslint plugin and config in [NPM](https://www.npmjs.com/search?q=eslint-plugin%7Ceslint-config)
